### ISSUE TITLE
Open311-Standard unterstützen

### ISSUE THREAD

**Issue by Matthias84** [rostock/klarschiff-frontend#37]
Mit http://open311.org gibt es einen Standard, mit dem platform-übergreifend Meldungen an lokale Behörden zugestellt werden können. Vielleicht kann so ein nativer mobiler Client mitgenutzt werden und die Zusammenführung aller Platformen in einer Meta-Platform ermöglicht werden?

**Comment by kvlahrosch** [comment]
Kommt bald!
